import type { MatchData } from "@/lib/types";

export const DEMO_MATCH: MatchData = {
  id: "demo-barca-rivals",
  providerId: null,
  competition: "Test match · Local beta",
  date: "Next match test sheet",
  kickoff: new Date().toISOString(),
  venue: "Estadi Olímpic",
  status: "Test mode",
  statusShort: "FT",
  home: {
    providerId: 529,
    name: "FC Barcelona",
    shortName: "BAR",
    logoUrl: "https://media.api-sports.io/football/teams/529.png",
  },
  away: { name: "Rivals", shortName: "RIV" },
  homeScore: 3,
  awayScore: 1,
  formation: "4–3–3",
  source: "demo",
  players: [
    { id: "demo-gk", name: "Goalkeeper", short: "Keeper", number: 1, role: "GK", roleLabel: "Sweeper goalkeeper", x: 50, y: 88, starter: true, played: true },
    { id: "demo-rb", name: "Right Back", short: "Right back", number: 2, role: "FB", roleLabel: "Right-back", x: 82, y: 72, starter: true, played: true },
    { id: "demo-rcb", name: "Right Centre-back", short: "RCB", number: 4, role: "CB", roleLabel: "Centre-back", x: 61, y: 75, starter: true, played: true },
    { id: "demo-lcb", name: "Left Centre-back", short: "LCB", number: 5, role: "CB", roleLabel: "Centre-back", x: 39, y: 75, starter: true, played: true },
    { id: "demo-lb", name: "Left Back", short: "Left back", number: 3, role: "FB", roleLabel: "Left-back", x: 18, y: 72, starter: true, played: true },
    { id: "demo-pivot", name: "Holding Midfielder", short: "Pivot", number: 6, role: "PIVOT", roleLabel: "Pivot", x: 50, y: 59, starter: true, played: true },
    { id: "demo-rm", name: "Right Interior", short: "R. interior", number: 8, role: "MID", roleLabel: "Interior midfielder", x: 68, y: 48, starter: true, played: true },
    { id: "demo-lm", name: "Left Interior", short: "L. interior", number: 20, role: "MID", roleLabel: "Attacking interior", x: 32, y: 48, starter: true, played: true },
    { id: "demo-rw", name: "Right Winger", short: "Right wing", number: 10, role: "WING", roleLabel: "Right winger", x: 78, y: 27, starter: true, played: true },
    { id: "demo-st", name: "Centre Forward", short: "Striker", number: 9, role: "ST", roleLabel: "Striker", x: 50, y: 22, starter: true, played: true },
    { id: "demo-lw", name: "Left Winger", short: "Left wing", number: 11, role: "WING", roleLabel: "Left winger", x: 22, y: 27, starter: true, played: true },
    { id: "demo-sub-1", name: "First Substitute", short: "Sub one", number: 16, role: "MID", roleLabel: "Interior midfielder", starter: false, played: true, minute: 63 },
    { id: "demo-sub-2", name: "Second Substitute", short: "Sub two", number: 7, role: "ST", roleLabel: "Striker", starter: false, played: true, minute: 72 },
    { id: "demo-sub-3", name: "Third Substitute", short: "Sub three", number: 14, role: "MID", roleLabel: "Interior midfielder", starter: false, played: true, minute: 81 },
  ],
};
